version: '3.8'
services:
  web-service:
    build: ./src
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - service-db
    environment:
      - MYSQL_HOSTNAME=service-db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vcs
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password

  service-db:
    build: ./db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vcs
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
